name: ⚙️ CI
on:
  push:
    # branches: [ master ]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "**/*.png"
      - "**/*.svg"

  pull_request:
    # branches: [ master ]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "**/*.png"
      - "**/*.svg"

jobs:
  unit-tests-godot-4-2:
    name: "⚙️ Unit tests - Godot 4.2.1"
    uses: ./.github/workflows/unit_tests.yml
    with:
      repo-ref: ${{ github.ref }}
      godot-version: 4.2.1-stable
      gut-tag: v9.3.0
  unit-tests-godot-4-4:
    name: "⚙️ Unit tests - Godot 4.4.1"
    uses: ./.github/workflows/unit_tests.yml
    with:
      repo-ref: ${{ github.ref }}
      godot-version: 4.4.1-stable
      gut-tag: v9.4.0
  unit-tests-godot-4-5:
    name: "⚙️ Unit tests - Godot 4.5"
    uses: ./.github/workflows/unit_tests.yml
    with:
      repo-ref: ${{ github.ref }}
      godot-version: 4.5-stable
      gut-tag: v9.5.0
